services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    ports:
      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data