services:
  redis:
    container_name: redis
    hostname: redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test