socket:
  retry:
    max-attempts: 3
  tcp:
    port: 3000
    host: localhost
  udp:
    port: 3001
    host: localhost

quarkus:
  log:
    level: INFO
  datasource:
    db-kind: postgresql
    username: elena.ferro
    password: Apyb2nkw
    reactive:
      url: vertx-reactive:postgresql://localhost:7001/vbx_comm
  hibernate-orm:
    database:
      generation: none
    scripts:
      generation: none

  redis:
    hosts: redis://localhost:6379