socket:
  retry:
    max-attempts: 3
  tcp:
    port: 3000
    host: localhost
  udp:
    port: 3001
    host: localhost

quarkus:
  log:
    level: INFO
  datasource:
    db-kind: postgresql
    username: quarkus_test
    password: quarkus_test
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/quarkus_test
  hibernate-orm:
    database:
      generation: drop-and-create
  redis:
    hosts: redis://localhost:6379